
import {
  LayoutDashboard,
  PenTool,
  Calendar,
  Clock,
  CreditCard,
  User,
  Users,
  ShieldCheck,
  LogOut,
  Settings,
  Bell,
  Search,
  BookOpen,
  Trophy,
  Flame,
  Plus,
  StickyNote,
  Type,
  Image as ImageIcon,
  MousePointer2,
  Download,
  Share2,
  MoreVertical,
  CheckCircle2,
  Circle,
  MessageCircle,
  Sparkles,
  Trash2,
  Target,
  Play,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  RefreshCw,
  Send,
  Lightbulb,
  Zap,
  Upload,
  Globe,
  Star,
  ExternalLink,
  FileText,
  Phone,
  Mic,
  MicOff,
  Video,
  VideoOff,
  X,
  AlertCircle,
  Eye,
  EyeOff,
  Copy,
  Link,
  Lock,
  Edit,
  TrendingUp,
  TrendingDown,
  UserPlus,
  Heart,
  Key
} from 'lucide-react';
import { StudyBoard, Activity, Task } from './types';

// Store the component definitions, not the rendered elements.
export const ICONS = {
  Dashboard: LayoutDashboard,
  StudyBoard: PenTool,
  Planner: Calendar,
  Calendar: Calendar,
  Focus: Clock,
  Clock: Clock,
  Flashcards: CreditCard,
  Profile: User,
  Users: Users,
  Admin: ShieldCheck,
  Logout: LogOut,
  Settings: Settings,
  Notification: Bell,
  Search: Search,
  Book: BookOpen,
  Trophy: Trophy,
  Flame: Flame,
  Plus: Plus,
  plus: Plus,
  StickyNote: StickyNote,
  Type: Type,
  Image: ImageIcon,
  Pointer: MousePointer2,
  Download: Download,
  download: Download,
  Share: Share2,
  share: Share2,
  Menu: MoreVertical,
  Check: CheckCircle2,
  check: CheckCircle2,
  CheckCircle: CheckCircle2,
  Uncheck: Circle,
  Chat: MessageCircle,
  Sparkles: Sparkles,
  Trash: Trash2,
  trash: Trash2,
  Target: Target,
  Play: Play,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronDown: ChevronDown,
  refresh: RefreshCw,
  send: Send,
  close: X,
  fileText: FileText,
  lightbulb: Lightbulb,
  zap: Zap,
  Zap: Zap,
  Upload: Upload,
  X: X,
  globe: Globe,
  star: Star,
  externalLink: ExternalLink,
  book: BookOpen,
  FileText: FileText,
  Phone: Phone,
  Mic: Mic,
  MicOff: MicOff,
  Video: Video,
  VideoOff: VideoOff,
  AlertCircle: AlertCircle,
  Eye: Eye,
  Copy: Copy,
  Link: Link,
  Lock: Lock,
  PenTool: PenTool,
  Edit: Edit,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  UserPlus: UserPlus,
  Send: Send,
  Heart: Heart,
  Bell: Bell,
  EyeOff: EyeOff,
  Key: Key,
};

// ⚠️ REMOVED MOCK DATA - Fetch from backend API instead
// Use studyBoardService.getUserBoards() to get real boards
export const MOCK_BOARDS: StudyBoard[] = [];

// ⚠️ REMOVED MOCK DATA - Fetch from backend API instead
// TODO: Create activity feed endpoint on backend
export const MOCK_ACTIVITIES: Activity[] = [];

// ⚠️ REMOVED MOCK DATA - Fetch from backend API instead
// Use planner service to get real tasks
export const MOCK_TASKS: Task[] = [];
